### ISSUE TITLE
Assignment isn't parsed correctly, but as keyword

### ISSUE THREAD

**Issue by salenaer** [smarr/SOMns#108]
when writing the target variable and the assignment operator without space this is read as method: =
for example 
arg:=value
(actor<-: message) whenResolved: [:arg | value:= arg].

error
value: tried to parse primary expression found equal.

**Comment by smarr** [comment]
Might be fixable, but requires lookahead on parsing keywords.
Also, switching to proper Newspeak setter sends (#7) would make this unnecessary.

**Comment by smarr** [comment]
Issue solved/avoided with #170.
