### ISSUE TITLE
Switch to new Graal Repository

### ISSUE THREAD

**Issue by smarr** [smarr/SOMns#133]
Oracle Labs decided to merge the [Truffle](https://github.com/graalvm/truffle) and [Graal](https://github.com/graalvm/graal-core) repositories into one new [Graal](https://github.com/graalvm/graal) repository.

Currently, we use a project setup with an external copy of Graal, so that it can be shared between multiple copies of SOMns, TruffleSOM, Grace, etc. Each project uses its own copy of Truffle and is able to update independently.

So, it looks roughly like this:

```
Projects
|- GraalBasic
|- SOMns
  |- libs
     |- truffle
|- TruffleSOM
  |- libs
     |- truffle
...
```

Since we maintain our own patches on top of Truffle, we need a fork of the Graal repo.

My initial proposal would be to have a separate copy of Graal for each project.
So, we would have a situation like this:

```
Projects
|- SOMns
  |- libs
     |- graal
|- TruffleSOM
  |- libs
     |- graal
...
```

This means, we might need to compile Graal for each project, which might or might not be an issue.
Especially for the build server, I would like to preserve the ability to use a common Graal compilation however.
So, that needs to be solved.

Another issue is the size of the history of Graal and other submodules.
This gets annoying, on the build server, as well as locally, because the downloads alone can take ages.

But there might be a solution here:

https://git-scm.com/docs/git-submodule (`submodule.<name>.shallow`)
http://stackoverflow.com/questions/2144406/git-shallow-submodules

Since this is going to be major change for how the project is setup and used, I would like to get input and ideas from you guys: @ctrlpz @daumayr @richard-roberts @salenaer

We also need to adapt the README and https://github.com/SOM-st/som-st.github.io/blob/master/somns/getting-started.md accordingly.

##### TODO
- [x] update README
- [x] update https://github.com/SOM-st/som-st.github.io/blob/master/somns/getting-started.md

**Comment by smarr** [comment]
One extra element to consider is that we will likely get another repository with a few shared source components that built on Truffle.
Current code name: BlackDiamonds.

So, it is likely going to look something like this:

```
Projects
|- SOMns
  |- libs
    |- graal
      |- compiler
      |- truffle
    |- black-diamonds
|- TruffleSOM
  |- libs
    |- graal
      |- compiler
      |- truffle
    |- black-diamonds
```

**Comment by richard-roberts** [comment]
Can't ANT download builds from a server during builds? If so, we could manage a repository of Graal builds (for each OS and each version we use in each project). ANT would then check that it has a viable build and if not download the appropriate one from the server. Maybe it's too much work, but one benefit is that places any concerns regarding Graal onto whoever manages the server and no one else.

**Comment by smarr** [comment]
Well, we have something like that already for the SOMns-deps jar.
That's code that changes very infrequently.
So, I build it and upload it.
See https://github.com/smarr/SOMns-deps/blob/master/upload.sh

The question is whether it is worth the effort of doing that for Graal binaries.
Someone using Graal to develop SOMns will in the end very likely be able to build it themselves anyway. For debugging, for IGV, etc.
So, I am not sure it's all that useful.
And you got the OS issue, which makes it so much more complicated.

**Comment by richard-roberts** [comment]
Hmm, yeah probably not worth the effort. In that case, I think the structure you mentioned above is reasonable. 

What's your opinion on managing the submodules? Should we maintain a top-level configuration file (I'm imagining something like [Python's requirements](https://pip.readthedocs.io/en/1.1/requirements.html)) that someone links into the ANT build script or maybe even the MX build tool?

**Comment by smarr** [comment]
What do you mean with 'top-level configuration'? 

Something that goes beyond this?

```
$ cat .gitmodules
[submodule "libs/truffle"]
	path = libs/truffle
	url = https://github.com/smarr/Truffle.git
[submodule "libs/mx"]
	path = libs/mx
	url = https://github.com/smarr/mx.git
```

**Comment by richard-roberts** [comment]
So, the top level configuration exists in the repo as a simple text file.

```
Projects
|- SOMns
  |-  requirements.txt
  |-  src
  |-  core-lib
  |-  ...
```

And contains the version numbers of Graal, TruffleSOM, and the diamonds that the developer wants:

```
graal: 0.4
truffleSOM: 0.7
diamonds:
  lexicalBuilder: 0.3
  eagerPrims: latest
  ...
```

Then we have some kind of build script (bash, ANT, MX, make) that can be executed to read in that configuration and check the requirements against what is currently in the directory. If there are any mismatches, the build script automatically uses git to checkout the appropriate version of the submodule.

**Comment by smarr** [comment]
how is that different from git using commit ids to ensure exactly that?
The only difference I see is that you have user readable version numbers.
But, that's only relevant once we have something stable, I think.
