### ISSUE TITLE
Unexpected behaviour when invoking block with return node

### ISSUE THREAD

**Issue by richard-roberts** [smarr/SOMns#174]
When I invoke the `value: _` method on a block that contains a return statement, the block's return expressions cause its enclosing method to terminate and return. 

For example, say I create a block that returns different things based on the value of a parameter:

```
public main: args = (
  | a |
  a := [ :i |
    i = 1 ifTrue: [^ 101].
    i = 2 ifTrue: [^ 102].
    ^ 103.
  ].
  ...
```

And then invoke this block inside the main method:

```
  ...
  'Start' println.
  (a value: 1) println.
  (a value: 2) println.
  (a value: 3) println.
  'End' println.
  ^ 0
)
```

Executing this program outputs `Start` and then `main: args` terminates. I think this incorrect, based on the definition given in the Newspeak spec (see 7.2):

> A return statement has the form *e*, where e is an expression. Execution of such a return statement in the context of an activation *a* causes *e* to be evaluated in the context of *a*. Then, if *a* is a method activation, control is passed to *a*’s continuation object (3.6), with the result of the evaluation of *e*. Otherwise, ***a* is a closure activation, and control is passed to the continuation object of *a*’s enclosing method activation**. 

Since the block is a closure activation, should it not be the case that my block (from my example above) should be able to return and then my `main: args` method to continue (from after the expression that invokes my block)?

**Comment by smarr** [comment]
I am pretty sure this is correct and spec-compliant.
`^ 103` is a non-local return.
You highlight the right part in the spec, I suppose.

a is a closure activation. a's continuation object would start at the `...`, I guess.
However, the spec says that not a's continuation but the continuation of a's enclosing method (`#main:`) is used. Thus, we return from `#main:`.

**Comment by richard-roberts** [comment]
I agree that `^ 103` should cause `#main:` to terminate, but how about `^ 102` and `^ 103`? 

As an example:

```
class Example usingPlatform: platform = Value ()(
  
  public main: args = (
    | a |
    a := [ :i |
      i = 1 ifTrue: [^ 101].
      i = 2 ifTrue: [^ 102].
      'Not found'
    ].

    'Start' println.
    (a value: 1) println.
    (a value: 2) println.
    (a value: 3) println.
    'End' println.
    ^ 0
  )
)
```

I would expect to see the output:

```
Start
101
102
Not found
End
```

But instead I just see `Start` (and then `main:` terminates).  

If this is the expected behaviour, then I cannot see how return expressions can be used to return a value from a block based on an argument. If so, is there sense in implemented a return expression that would enable this?

**Comment by smarr** [comment]
Why is it any different for `^ 101` and `^ 102`?
It is still the same part of the spec that applies. The enclosing method is terminated.
`#main:` is the only method around, so, main is left.

Returning a value from a block is easy. The last expression's value is returned implicitly.

`assert: 3 equals: [ 4 - 1 ] value` will hold.
And extra 'local return operator' seems rarely useful. I think, Smalltalk programmer would argue that your code is too complex if you need one, and you should try to restructure it instead.
