### ISSUE TITLE
Optimize Exception signaling

### ISSUE THREAD

**Issue by daumayr** [smarr/SOMns#214]
Build a nice exception thrower in Java to avoid helpers in SOMns code.
Introduction of new Exception classes (and throwing them from the Java side) should be clean and easy to do.

**Comment by smarr** [comment]
TODO:

- [x] make sure all `signalNotAValueWith:` errors and similar use only the class of the broken `Value`, but don't let the invalid `Value` object escape. We can't allow references to invalid objects to exist
- [x] make sure we use constant `SSymbol` objects everywhere, the string conversion is just overhead

**Comment by clementbera** [comment]
Attempted to fix in PR:
https://github.com/smarr/SOMns/pull/251
