### ISSUE TITLE
Use of com.sun.istack.internal.*

### ISSUE THREAD

**Issue by potanin** [smarr/SOMns#235]
Hello,

Several places (e.g. src/som/interpreter/actors/SPromise.java, src/som/compiler/MixinDefinition.java, src/som/compiler/MethodBuilder.java, and src/tools/dym/profiles/OperationProfile.java) make use of com.sun.istack.internal.NotNull or com.sun.istack.internal.Nullable which make it harder to build with typical error that "package com.sun.istack.internal is not visible". Is there any chance these can be removed?

Thanks,
Alex.

**Comment by potanin** [comment]
Note that I don't have this issue in "dev" branch which presumably was cleaned up?

**Comment by smarr** [comment]
The dev branch is the development branch with the latest changes. Master is going to be updated with the next release only. Sorry for the confusion.
