### ISSUE TITLE
Prepare SOMns v0.6.0 release

### ISSUE THREAD

**Issue by smarr** [smarr/SOMns#236]
This is the issue to track the final tasks for the SOMns v0.6.0 release, which is tracked via the [v0.6.0 milestone](https://github.com/smarr/SOMns/milestone/7).

### Extra Changes

- [x] rename `master` to `release` to communicate more clearly how we use the master branch.
- [x] ~~update Truffle to latest version (don't do any changes that are not necessary, can be done later)~~
- [x] setup testing for [Java 10](http://jdk.java.net/10/)
- [x] ensure https://github.com/SOM-st/black-diamonds/issues/10 is fixed

### Release Checklist

This list is supposed to make sure we do not forget any important steps during 
release. It is based on https://github.com/smarr/SOMns/blob/dev/docs/release-checklist.md

- [x] 1. Check and update issue tracker for issues associated with current milestone

- [x] 2. Update CHANGELOG.md with all elements missing
   A useful tool is the `github_changelog_generator`  
   It can be used like this:

        sudo gem install github_changelog_generator
        github_changelog_generator -u smarr -p SOMns -o changelog-gen.md --since-tag v0.5.0 --token ${GITHUB_TOKEN}

- [x] 3. Make sure all desired changes are part of the `dev` branch.

- [x] 4. Prepare a release on GitHub with: https://github.com/smarr/SOMns/releases/new
   The content is normally just the last part of the CHANGELOG.md

- [x] 5. If everything looks good, tag the release using the GitHub feature

- [x] 6. Push the commit that is tagged as release to the `release` branch.

- [x] 7. Announce the release
  - https://groups.google.com/forum/#!forum/som-dev
  - https://twitter.com/SOM_VMs

@daumayr @richard-roberts if you need something, anything, please chime in as soon as possible.

**Comment by smarr** [comment]
Java 10 just got release: http://jdk.java.net/10/
So, one extra todo should be to enable testing for it.

And, we probably want to update Truffle before the release, too.

@richard-roberts what's your target date for a Moth release?

**Comment by ghost** [comment]
I'm on no particular deadline to create a 0.1 release for Moth, but ideally, it's done before the end of March. Let's say April 01, which at least has some comical benefit.

**Comment by smarr** [comment]
@richard-roberts @daumayr As it turns out updating Truffle is a major project, which I can't do myself at the moment. Are you aware of any issues that would require a more up to date Truffle/Graal?

Problems with the new Truffle version I am aware of:
- changed approach to instrumentation wrappers, requires careful redesign, possibly adaptation of node hierarchy
- changes in debugger support, stepping strategies, filters, etc. requires changes and reimplementation of custom patches
- issues with javac https://markmail.org/thread/niy4a6cyd76mwspj

If there are no important reasons, I'll postpone the Truffle update, and release with the Truffle we got now.

**Comment by daumayr** [comment]
I don't have any issues with the current truffle/graal

**Comment by smarr** [comment]
And that's it for 0.6.0: https://github.com/smarr/SOMns/releases/tag/v0.6.0

**Comment by ghost** [comment]
Thanks for all the fish!
