### ISSUE TITLE
Refactor Native Image Support (SubstrateVM) to avoid hard dependency

### ISSUE THREAD

**Issue by smarr** [smarr/SOMns#327]
Looks like @fniephaus managed without it: https://github.com/hpi-swa/graalsqueak/commit/295027cf79b1e888d3c091da3fc462aee22a80bc

So, would probably simplify things.

**Comment by fniephaus** [comment]
https://github.com/smarr/SOMns/commit/f47afbdd24f93c8c7c9b5e4ccf5c643734d2591e is the commit introducing most of the code that can now be simplified.

**Comment by smarr** [comment]
We can't avoid the dependency on SVM core, because we want to announce the classes used for the Kompos protocol to the reflection support.
Though, @fniephaus simplified the offset calculation with #328.
