### ISSUE TITLE
Use JSON library to reduce boilerplate code

### ISSUE THREAD

**Issue by smarr** [smarr/SOMns#35]
Gson, which is already used in the language server might be a good alternative to manually serializing the data.

Goal is to remove the code and cleanup the related code structure. At the moment, it seems to be quite a mess.
One problem is the different tools that have some dependencies now.

**Comment by goti921** [comment]
I would like to contribute. Any details on how to start with this?

**Comment by smarr** [comment]
Hi @goti921 this is not a very good starter project unfortunately. I am working on rather extensive refactorings that require intimate knowledge of the system.

Another more entry-level issues you could try yourself on is this: https://github.com/smarr/SOMns/issues/18 see the links for a solution in TruffleSOM.
Depending on your background, there might be other things that could interest you, which are not necessarily in the issue tracker at the moment.

**Comment by goti921** [comment]
Ok @smarr 
Thanks for the prompt reply.

**Comment by smarr** [comment]
Was resolved with #38.
